

# Site settings
title: JWM
email: jordanwhitneymartin@gmail.com
description: portfolio site for jordan whitney martin


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jordanwhitneym
  - title: github
    url: http://github.com/jwbmartin
  - title: instagram
    url: https://www.instagram.com/jordanwhitneym


# Build settings
markdown: kramdown
permalink: pretty